### ISSUE TITLE
single-platform case unnecessary

### ISSUE THREAD

**Issue by kylemcdonald** [ofZach/pgElectron#17]
i think when we are generating for a single platform (the one that this PG was packaged with for download) then the "platform" field might be unnecessary.

right now, for me it shows "Unknown" but maybe that has something to do with it not being initialized by default anywhere.

(i'm going to post a couple other things i noticed rather than compiling it in one issue/thread)

**Comment by ofZach** [comment]
I think showing it is useful for debugging / disambiguating.   we showed this on the original simple PG and i think it's useful (at least for me, I find it helpful to know that I am using the ios PG vs the osx one). 

it says undefined because the settings.json file is not up to date, I need to check in some changes.  I also think the "display" names of the platforms are a little thin, vs should be visual studio, etc.  I am working on that now.

**Comment by Daandelange** [comment]
You can change your default platform in settings.json
There's no auto-detect as this has to be packaged with the release files... but I'm still wondering how to make this work those who download the github repos.

Node-js has a platform detection feature; we might be able to use that ?
So it would be:
If there's a settings.json it uses the default platform from there, otherwise (for github repos) it auto-detects.

**Comment by ofZach** [comment]
i think this won't work for IOS.  We should just give instructions and put in OSX for now since we are testing it on OSX.    This was also a setting the settings.xml of the last PG so it's pretty similar to that.
