### ISSUE TITLE
window height should be smaller

### ISSUE THREAD

**Issue by kylemcdonald** [ofZach/pgElectron#20]
i suggest the default height is based on the "Create / Update" tab in "simple" mode. if it gets bigger with lots of addons, it's still possible to scroll.

**Comment by ofZach** [comment]
+1

**Comment by Daandelange** [comment]
Indeed, feels kind of weird having blank space at the bottom.
Did you fix this @ofZach ? _It got smaller with the last commits._

**Comment by ofZach** [comment]
yes - also I think we should generally remove the console on the main screen (and just have it on the project build / update action), then we can get very small :)

**Comment by ofZach** [comment]
I've done this in the latest commit...  I still want to look at overall design and spacing but closing this for now...

**Comment by Daandelange** [comment]
I moved the console to be relative so it hides on scroll but now it looks weird **when** there is blank space below the console. (saying because it's related to page height)

**Comment by ofZach** [comment]
I generally don't think the console is needed and it complicates the UI a bit.  I feel like just showing it once the action is done is enough, what do you think?

**Comment by Daandelange** [comment]
I like to have the whole console history for my personal use but I agree it complicates the UI a bit.
But hey! c++ is complicated! :tongue: 
No, without kidding, I'd feel bad not being able to trace it back; it gives useful information and otherwise vanishes after closing the modal. And it's still a setting which can be disabled.

Maybe we've got 2 ≠ settings: «Show console» and «Show console feedback»
And I still think it's weird to not show the console message when an error occured. (you have to have  console enabled)

_(Talking about the same thing in different issues :angel: )_

**Comment by ofZach** [comment]
I wonder if it's just better to do a show console log button somewhere in the UI that opens an overlay that you can close and to then drop the console from the overlay on generate / update ( and to make that a bit less instructive , simpler ).   I feel like they don't belong both places, and they it's wonky to keep adding settings.   I think it shouldn't be part of the UI but be more optional.   what do you think?
