### ISSUE TITLE
ui bugs at the moment(?)

### ISSUE THREAD

**Issue by kylemcdonald** [ofZach/pgElectron#27]
i'd like to contribute but i'm not really sure where this is right now. here's the experience i'm getting:
- after a fresh download of the git repo, after `npm start` the first thing i see is "no addons were found in /User/addons". but i would expect it to use ../../addons or similar on first startup.
- i go to settings and change the OF root manually
- i go to create/update and open a project with no addons. the addons field still says "No addons found, is OF path right?" even though i updated it already.
- i switch to an example with an addon: `example-simplePoints` inside `ofxDelaunay`. now the addons field updates to show the addon.
- i click "update project" but it gives me an error: "please select a platform first". it just says "Unknown" and i can't change it.
- i go to settings and turn on advanced settings.
- i come back and select "OS X" and hit "Update Project"
- i get an error:

```
Command failed: /bin/sh -c /Users/kyle/Documents/openFrameworks/pgElectron/app/commandLinePG  -o"/Users/kyle/Documents/openFrameworks" -a"ofxDelaunay" -x"osx" "/Users/kyle/Documents/openFrameworks/addons/ofxDelaunay/example-simplePoints"
/bin/sh: /Users/kyle/Documents/openFrameworks/pgElectron/app/commandLinePG: Permission denied
```
- i open terminal and cd to `pgElectron/app/` and `chmod +x commandLinePG`
- i do it again and it says "success". but when i look at the directory, there is no project file. from the i don't see any error messages in terminal.

**Comment by ofZach** [comment]
one issue I see is that settings.json is in the gitignore, so I think the current settings.json isn't totally up to date (and it's hard for me to see it, since my settings.json is right).  I've just pushed my settings so that you don't get undefined for platform, but you'll obviously need to change the path. 

also the PG that's in this repo seem out of date too (it's likely that @Daandelange updated the commands to the PG but not the projectGenerator app, which probably shouldn't be in this repo at all since it's kind of platform specific), so it's not happy with the parameters that are sent to it.  It also looks like our system needs some error checking, like looking if a folder is actually there.  (it's success right now is just if it ran the command line tool which seems wrong -- here, it's saying it succeeded when it didn't) 

please keep in mind that I am doing a UI rewrite right now in another branch (which is fairly unusable at the moment but should be up v. soon) -- my head is in that and not in this at the moment so there are alot of visual / ui things but I think the next version should make things much cleaner.

**Comment by ofZach** [comment]
(as a side note, if you run the command line PG and it says "no mode selected... please use create or update" that's a good sign that it's an older app, arturo and I worked through a bunch of changes to the command line to streamline the parameters, etc)

**Comment by Daandelange** [comment]
@ofZach : Yes, I updated the cmdLinePG to the latest commit and indeed; as it's platform specific I didn't include the binary. (I should have removed the original one maybe).
@kylemcdonald You can just build it, rename it and place it in `/app/app/commandLinePG`
-  "No addons found, is OF path right?" even though i updated it already
  This is an UI bug indeed. If you start typing the addons appear. I created #28 for this.

But it's weird that is says success while it's not been passed the right commands. Maybe the (new) command succeeds with the old cmdLinePG (but does something else as there are no more `-c` or `-u` flags) ?
Oh and I see `/bin/sh -c` in your command... which means you don't have the latest commit as it removes the `-c` flag.

As for platform Unknown, it reads it from `settings.json` which needs to be platform specific. When there's none it writes the settings from `index.js` (top) and platform is just set to "Unknown".
@ofZach said there will be a platform-specific `settings.json` so we don't have to care about it yet.
For the moment you can open `settings.json` and set the platform variable to `osx`.

But yeah, to sum up it's still in a messy state but thanks for reporting your experience. :)
Should go better soon when Zach's semantic-ui branch gets merged.

**Comment by ofZach** [comment]
I think it's fine to put in a platform specific json file for now, we are just testing now, it will help.  I pushed my json file if it's useful.

**Comment by Daandelange** [comment]
https://github.com/ofZach/pgElectron/commit/340b7a28d713fdbeea7c35d74b57a8502ffb81b4 I added a feature to detect the platforms too, only IOS remains to be detected. (that could be detected client-side (from the User-Agent string), or maybe server-side using the CPU info ?)

**Comment by kylemcdonald** [comment]
Cool! I'll keep watching for updates and testing. Daan, I don't think
platform detection will work for iOS because people will not run the
electron app on their iOS device, but from OSX.

**Comment by ofZach** [comment]
cool - the semantic-ui PR is more functional now (but not really working yet...) if you want to track that (I'm basically re-implementing alot of the stuff that was built on boostrap).  I think I am going to become a web designer now.   Jsfiddling my way to a working gui. 

<img width="527" alt="screen shot 2015-08-26 at 11 13 56 am" src="https://cloud.githubusercontent.com/assets/142897/9497580/aaec17d6-4be3-11e5-93f0-ca7fd69c73c4.png">
<img width="526" alt="screen shot 2015-08-26 at 11 14 12 am" src="https://cloud.githubusercontent.com/assets/142897/9497582/aaf68d06-4be3-11e5-971a-7ad7a847d79f.png">
<img width="539" alt="screen shot 2015-08-26 at 11 14 34 am" src="https://cloud.githubusercontent.com/assets/142897/9497581/aaf3cdb4-4be3-11e5-8f42-74ad1374ff05.png">

semantic ui is fairly clean and because we were merging two things before (select2 and bootstrap) the styling was wonky.  This feels more professional.  There's some some stuff to be done to make the chromeless window work well (it needs a close button, some info and dragging ability on the top bar) but it looks pretty cool to now have the window chrome. 

also the multi-select for the platforms (which gets disabled in non-advanced mode and set to default) seems a bit easier from a UI perspective...

**Comment by Daandelange** [comment]
Looks very nice! :+1: 
I love the new window format!
Ping me if/when you need help getting js stuff to work again! :)

**Comment by ofZach** [comment]
I think it's pretty straight forward, I just am moving more of the logic to JS and away from CSS (ie to show / hide elements) and semantic-ui is a little wonky in how it interacts with jquery (I find myself getting tripped up a little).  I have most buttons / fields hooked up now and the fields have data that is changing :) I will dig deeper later today on the overlays and some more state stuff / bugs. 

PS: the moniker stuff is pretty hilarious.

**Comment by Daandelange** [comment]
Hmm, well I did the CSS/hiding on purpose so that with JS you handle (or indicate) the app's state then the CSS handles all the rest depending on the app's state. This way you have cleaner code because all the appearance stuff is moved out of the JS files.
But I'll leave it up to you if you think it's easier the JS way. :)

PS: Yes it is ;D

**Comment by kylemcdonald** [comment]
ok, looks very nice. going to hold off on further testing/comments/tweaks till you think it's ready.

**Comment by ofZach** [comment]
it's not 100% done but the semantic-ui PR branch can now do single project generation and updating (I need to hook up multiple / recursive updates and the modal dialogs are missing now, working on getting those back).   def worth taking a look at now, now that it's more functional....  more updates shortly.

**Comment by Daandelange** [comment]
Modal dialogs: :white_check_mark: eedeed6
I also discovered a better search-term-matchin-function for the addons dropdown: fcf35b2

**Comment by ofZach** [comment]
thanks! I was starting to look at this for form validation http://semantic-ui.com/behaviors/form.html might be a little less intrusive then the modals, but it's good to have them back :)
